# Generated by Django 2.2.3 on 2019-08-08 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowd_surfer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='funding_goal',
            field=models.IntegerField(default=10000),
            preserve_default=False,
        ),
    ]
