# Generated by Django 2.2.3 on 2019-08-08 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowd_surfer', '0004_auto_20190808_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crowd_surfer.Project'),
            preserve_default=False,
        ),
    ]
