# Generated by Django 2.2.4 on 2019-08-09 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowd_surfer', '0005_reward_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='crowd_surfer.Project'),
        ),
    ]
