# Generated by Django 2.2.4 on 2019-08-09 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowd_surfer', '0006_auto_20190809_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='reward_limit',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
