# Generated by Django 2.2.3 on 2019-08-09 19:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowd_surfer', '0007_auto_20190809_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='backers',
            field=models.ManyToManyField(null=True, related_name='projects_backed', to=settings.AUTH_USER_MODEL),
        ),
    ]
