# Generated by Django 2.2.3 on 2019-08-09 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowd_surfer', '0008_auto_20190809_1928'),
        ('crowd_surfer', '0007_reward_reward_limit'),
    ]

    operations = [
    ]
