# Generated by Django 2.2.4 on 2019-08-09 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowd_surfer', '0008_auto_20190809_1928'),
        ('crowd_surfer', '0007_reward_reward_limit'),
    ]

    operations = [
    ]
