# Generated by Django 2.2.4 on 2019-08-10 01:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crowd_surfer', '0014_auto_20190810_0120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.ManyToManyField(related_name='profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
