# Generated by Django 2.2.4 on 2019-08-10 01:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowd_surfer', '0015_auto_20190810_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.ManyToManyField(related_name='user_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
