# Generated by Django 2.2.4 on 2019-08-10 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowd_surfer', '0017_auto_20190810_0136'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
