# Generated by Django 2.2.4 on 2019-08-10 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowd_surfer', '0018_delete_profile'),
        ('crowd_surfer', '0009_merge_20190809_2045'),
    ]

    operations = [
    ]
