# Generated by Django 2.2.4 on 2019-08-11 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowd_surfer', '0019_merge_20190810_0233'),
        ('crowd_surfer', '0010_auto_20190810_1603'),
    ]

    operations = [
    ]
